apiVersion: v1
kind: Namespace
metadata:
  name: opengnosis
  labels:
    name: opengnosis
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: opengnosis-dev
  labels:
    name: opengnosis-dev
    environment: development
---
apiVersion: v1
kind: Namespace
metadata:
  name: opengnosis-staging
  labels:
    name: opengnosis-staging
    environment: staging
